Repository Asilo5/Ballroom-Beats-UI, pull requests merged in 2020-02, with the labels that each got.

#6 Set files
  ballroom-beats/.expo-shared/assets.json
  ballroom-beats/.gitignore
  ballroom-beats/App.js
  ballroom-beats/app.json
  ballroom-beats/assets/icon.png
  ballroom-beats/assets/splash.png
  ballroom-beats/babel.config.js
  ballroom-beats/package-lock.json
  ballroom-beats/package.json
Labels: Files Added, Frontend, React-Native

#39 Start testing
  ballroom-beats/.vscode/settings.json
  ballroom-beats/App.test.js
  ballroom-beats/__snapshots__/App.test.js.snap
  ballroom-beats/apiCalls.js
  ballroom-beats/apiCalls.test.js
  ballroom-beats/coverage/clover.xml
  ballroom-beats/coverage/coverage-final.json
  ballroom-beats/coverage/lcov-report/ballroom-beats/App.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/apiCalls.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/index.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/setupTests.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/AppNavigator/AppNavigator.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/AppNavigator/index.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/DanceType/DanceType.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/DanceType/index.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/End/End.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/End/index.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/Game/Game.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/Game/index.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/Home/Home.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/Home/index.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/Loader/Loader.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/Loader/index.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/Navbar/Navbar.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/Navbar/index.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/Score/Score.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/Score/index.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/SongPick/SongPick.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/SongPick/index.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/SongPlayer/SongPlayer.js.html
  ballroom-beats/coverage/lcov-report/ballroom-beats/src/components/SongPlayer/index.html
  ballroom-beats/coverage/lcov-report/base.css
  ballroom-beats/coverage/lcov-report/block-navigation.js
  ballroom-beats/coverage/lcov-report/index.html
  ballroom-beats/coverage/lcov-report/prettify.css
  ballroom-beats/coverage/lcov-report/prettify.js
  ballroom-beats/coverage/lcov-report/sort-arrow-sprite.png
  ballroom-beats/coverage/lcov-report/sorter.js
  ballroom-beats/coverage/lcov.info
  ballroom-beats/package-lock.json
  ballroom-beats/package.json
  ballroom-beats/setupTests.js
  ballroom-beats/src/components/AppNavigator/AppNavigator.test.js
  ballroom-beats/src/components/DanceType/DanceType.test.js
  ballroom-beats/src/components/End/End.test.js
  ballroom-beats/src/components/Game/Game.test.js
  ballroom-beats/src/components/Home/Home.test.js
  ballroom-beats/src/components/Loader/Loader.test.js
  ballroom-beats/src/components/Navbar/Navbar.test.js
  ballroom-beats/src/components/Score/Score.test.js
  ballroom-beats/src/components/Score/__snapshots__/Score.test.js.snap
  ballroom-beats/src/components/SongPick/SongPick.test.js
  ballroom-beats/src/components/SongPlayer/SongPlayer.test.js
  ballroom-beats/src/components/SongPlayer/__snapshots__/SongPlayer.test.js.snap
Labels: Frontend, Testing

#50 Style dance
  ballroom-beats/src/components/DanceFloor/DanceFloor.js
  ballroom-beats/src/components/Dances/Waltz/Waltz.js
  ballroom-beats/src/components/Game/Game.js
Labels: Dance Floor, Frontend, Style

#52 Fix bug that was creating two waltz components
  ballroom-beats/src/components/Game/Game.js
Labels: Dance Floor, bug

#56 Add snapshots
  ballroom-beats/App.test.js
  ballroom-beats/__snapshots__/App.test.js.snap
  ballroom-beats/app.json
  ballroom-beats/package-lock.json
  ballroom-beats/package.json
  ballroom-beats/src/App/App.js
  ballroom-beats/src/App/App.test.js
  ballroom-beats/src/components/Dances/Waltz/Waltz.js
  ballroom-beats/src/components/Game/Game.js
  ballroom-beats/src/setupTests.js
Labels: Dance Floor, Frontend, React-Native, Style

#55 Aw edit pickers
  ballroom-beats/src/components/DanceType/DanceType.js
  ballroom-beats/src/components/Home/Home.js
  ballroom-beats/src/components/Loader/Loader.js
  ballroom-beats/src/components/Navbar/Navbar.js
  ballroom-beats/src/components/SongPick/SongPick.js
Labels: Frontend

#57 Build bachata
  ballroom-beats/src/components/DanceFloor/DanceFloor.js
  ballroom-beats/src/components/Dances/Bachata/Bachata.js
  ballroom-beats/src/components/Dances/Bachata/Bachata.test.js
Labels: Bachata, Dance Floor, Frontend

#61 Add logo
  ballroom-beats/images/logo_transparent.png
  ballroom-beats/package-lock.json
  ballroom-beats/package.json
  ballroom-beats/src/components/DanceFloor/DanceFloor.js
  ballroom-beats/src/components/DanceType/DanceType.js
  ballroom-beats/src/components/End/End.js
  ballroom-beats/src/components/Game/Game.js
  ballroom-beats/src/components/Home/Home.js
  ballroom-beats/src/components/Loader/Loader.js
  ballroom-beats/src/components/Navbar/Navbar.js
  ballroom-beats/src/components/SongPick/SongPick.js
Labels: Dance Floor, Dashboard, Frontend, Style, enhancement

#63 Test testing
  ballroom-beats/coverage/clover.xml
  ballroom-beats/coverage/coverage-final.json
  ballroom-beats/coverage/lcov-report/AppNavigator/AppNavigator.js.html
  ballroom-beats/coverage/lcov-report/AppNavigator/index.html
  ballroom-beats/coverage/lcov-report/DanceType/DanceType.js.html
  ballroom-beats/coverage/lcov-report/DanceType/index.html
  ballroom-beats/coverage/lcov-report/Loader/Loader.js.html
  ballroom-beats/coverage/lcov-report/Loader/index.html
  ballroom-beats/coverage/lcov-report/Navbar/Navbar.js.html
  ballroom-beats/coverage/lcov-report/Navbar/index.html
  ballroom-beats/coverage/lcov-report/Score/Score.js.html
  ballroom-beats/coverage/lcov-report/Score/index.html
  ballroom-beats/coverage/lcov-report/SongPick/SongPick.js.html
  ballroom-beats/coverage/lcov-report/SongPick/index.html
  ballroom-beats/coverage/lcov-report/SongPlayer/SongPlayer.js.html
  ballroom-beats/coverage/lcov-report/SongPlayer/index.html
  ballroom-beats/coverage/lcov-report/index.html
  ballroom-beats/coverage/lcov.info
  ballroom-beats/package.json
  ballroom-beats/src/App/App.test.js
  ballroom-beats/src/components/AppNavigator/AppNavigator.js
  ballroom-beats/src/components/AppNavigator/AppNavigator.test.js
  ballroom-beats/src/components/DanceType/DanceType.js
  ballroom-beats/src/components/DanceType/DanceType.test.js
  ballroom-beats/src/components/End/End.test.js
  ballroom-beats/src/components/End/__snapshots__/End.test.js.snap
  ballroom-beats/src/components/Loader/Loader.js
  ballroom-beats/src/components/Loader/Loader.test.js
  ballroom-beats/src/components/Navbar/Navbar.js
  ballroom-beats/src/components/Navbar/Navbar.test.js
  ballroom-beats/src/components/Navbar/__snapshots__/Navbar.test.js.snap
  ballroom-beats/src/components/Score/Score.js
  ballroom-beats/src/components/SongPick/SongPick.js
  ballroom-beats/src/components/SongPick/SongPick.test.js
  ballroom-beats/src/components/SongPlayer/SongPlayer.js
  ballroom-beats/src/components/SongPlayer/SongPlayer.test.js
Labels: Frontend, Testing

#79 Aw modify styles android
  ballroom-beats/src/components/DanceType/DanceType.js
  ballroom-beats/src/components/End/End.js
  ballroom-beats/src/components/Home/Home.js
  ballroom-beats/src/components/Loader/Loader.js
  ballroom-beats/src/components/Navbar/Navbar.js
  ballroom-beats/src/components/SongPick/SongPick.js
Labels: Frontend

#80 Add animation
  ballroom-beats/package-lock.json
  ballroom-beats/package.json
  ballroom-beats/src/components/Comments/Comments.js
  ballroom-beats/src/components/Comments/Comments.test.js
  ballroom-beats/src/components/Dances/Waltz/Waltz.js
Labels: Animation, Frontend, Style, enhancement

#82 Add left right indication
  ballroom-beats/src/components/Dances/Waltz/Waltz.js
Labels: Dance Floor, Frontend, Style, enhancement
